name: Short link Backend Build and K8s Cluster Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-k8s-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.21.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind version

      - name: Start Kind Cluster and Deploy Dependencies
        run: |
          bash bin/k8s-up-all.sh
          
          # Deploy Postgres *2 and Redis *1 for Project Mvn Verify
          # TODO: here we gonna add shortlink-service & shortlink-admin yamls to prod folder
          # then here we gonna setup prod env with monitor, istio, admin and shortlink-svc ready 
          # TODO: kubectl apply -k k8s/overlays/prod/
          kubectl apply -k k8s/overlays/prod/
          
          # Waiting for all pods running 
          echo "Waiting 30s for PostgreSQL and Redis to be ready..."
          sleep 30

      - name: Get All Pods, Svcs Deployed on Kind in namespace shortlink
        run: |
          echo "pending for 30s, wait for all svc and pods get ready"
          sleep 30
          
          echo "all pods in shortlink namespace"
          kubectl get pods -n shortlink 
          
          echo "all services in shortlink namespace"
          kubectl get svc -n shortlink

      - name: Port-forward PostgreSQL and Redis
        run: |
          bash bin/port-forward.sh

      - name: Verify Project
        run: |
          mvn clean verify -DskipTest

      - name: Shutdown Kind Cluster
        if: always()
        run: |
          bash bin/k8s-down.sh

